{
    'invoiceID': '1599749413',
    'invUNP': '1599749413',
    'invoiceStateID': '1',
    'invoiceState': 'Заготовка',
    'invLastOper': '26.02.2025 05:14:19',
    'invNeedForECP': '2',
    'invECPSign': '1',
    'invDateCreate': '26.02.2025 05:14:18',
    'invTypeID': '1',
    'invTypeName': 'Накладная на погрузку',
    'invBlankTypeID': '182',
    'invBlankType': '94',
    'invBlankTypeName': 'ГУ-27у (ГУ-27уВЦ) единый',
    'invSenderID': '622082',
    'invSenderOKPO': '42876737',
    'invSenderName': 'Общество с ограниченной ответственностью "Транспортные Технологии"',
    'invSenderAddressID': '0',
    'invSenderAddress': '143026, МОСКОВСКАЯ ОБЛАСТЬ, г.о. Одинцовский, г.Одинцово, р.п.Новоивановское, Можайское шоссе, дом 165 - этаж 2 - блок D, тел: 84951815200',
    'invSenderTGNL': '4319',
    'invFromCountryCode': '643',
    'invFromCountryName': 'РОССИЯ',
    'invFromStationCode': '87170',
    'invFromStationName': 'ЛАТЫШИ',
    'invRecipID': '5005053',
    'invRecipOKPO': '82365518',
    'invRecipName': 'Акционерное общество "АТРИУМ"',
    'invRecipAddressID': '0',
    'invRecipAddress': '654007, КЕМЕРОВСКАЯ ОБЛАСТЬ - КУЗБАСС, г. Новокузнецк, ул. Павловского - д. 11 А - оф. 508, тел: 8(3842) 44-00-81,8-910-407-2528',
    'invRecipTGNL': '4444',
    'invToCountryCode': '643',
    'invToCountryName': 'РОССИЯ',
    'invToStationCode': '87170',
    'invToStationName': 'ЛАТЫШИ',
    'invSendSpeedID': '2',
    'invSendSpeedName': 'Грузовая',
    'invSendKindID': '4',
    'invSendKindName': 'Групповая',
    'invPayPlaceID': '3',
    'invPayPlaceName': 'ЦФТО',
    'invPayFormID': '0',
    'invPayFormName': 'безналичный централизованный',
    'invPlanCarTypeID': '60',
    'invPlanCarTypeCode': '60',
    'invPlanCarTypeName': 'полувагоны',
    'invPlanCarCount': '3',
    'invPlanCarOwnerTypeID': '1',
    'invPlanCarOwnerTypeName': 'Собственный',
    'invPlanContOwnerTypeID': '3',
    'invPlanContOwnerTypeName': 'Принадлежат перевозчику',
    'invLoadTypeID': '11',
    'invLoadTypeName': 'БЕЗ ЗАЧЕТА В ПОГРУЗКУ',
    'invAnnounceValue': '0',
    'invAVCurrencyID': '1',
    'invLoadAssetsID': '1',
    'invLoadAssetsName': 'Отпр',
    'invDispKindID': '10',
    'invRespPerson': 'Николаев С.Н. Спецалист',
    'invPayerCode': '1005246582',
    'invPayerId': '622082',
    'invPayerName': 'ООО "Транспортные Технологии"',
    'invLoadClaim_ID': '1598330344',
    'invLoadClaim_Number': '0044604685-ИЗМ/1',
    'invCheckDepID': '2',
    'invCheckDepName': 'с бруса',
    'invDateLoad': '26.02.2025 00:00:00',
    'invDateExpire': '02.03.2025 00:00:00',
    'invNumber': 'ЭС204943',
    'invSignRouteNumCirc': '0',
    'invFreight': {
        'freightCode': '42119',
        'freightName': 'ВАГОНЫ ЖЕЛЕЗНОДОРОЖНЫЕ ПОРОЖНИЕ, ПЕРЕВОЗИМЫЕ НА СВОИХ ОСЯХ, ПЕРЕСЫЛАЕМЫЕ В РЕМОНТ ИЛИ ИЗ РЕМОНТА',
        'freightWeight': '0',
        'freightRealWeight': '0',
        'freightDangerSignID': '1',
        'freightDangerSignName': 'Неопасный груз',
        'freightID': '-890991283'
    },
    'invDistance': [
        {
            'distCountryCode': '643',
            'distCountryName': 'РОССИЯ',
            'distStationCountryId': '178',
            'distStationCode': '87170',
            'distStationName': 'ЛАТЫШИ',
            'distTrackTypeID': '1',
            'distTrackTypeName': 'Широкая',
            'distTranspTypeID': '1',
            'distTranspTypeName': 'Ж.Д.',
            'distMinWay': '5',
            'distRecipID': '622082',
            'distRecipOKPO': '42876737',
            'distRecipName': 'Общество с ограниченной ответственностью "Транспортные Технологии"',
            'distRecipAddressID': '0',
            'distRecipAddress': '143026, МОСКОВСКАЯ ОБЛАСТЬ, г.о. Одинцовский, г.Одинцово, р.п.Новоивановское, Можайское шоссе, дом 165 - этаж 2 - блок D, тел: 84951815200',
            'distRecipTGNL': '4319',
            'distPayerId': '622082',
            'distPayerCode': '1005246582',
            'distPayerName': 'ООО "Транспортные Технологии"',
            'distSign': '10101',
            'distCarrierID': '1',
            'distPowerKind': '1'
        },
        {
            'distCountryCode': '643',
            'distCountryName': 'РОССИЯ',
            'distStationCountryId': '178',
            'distStationCode': '87170',
            'distStationName': 'ЛАТЫШИ',
            'distTrackTypeID': '1',
            'distTrackTypeName': 'Широкая',
            'distTranspTypeID': '1',
            'distTranspTypeName': 'Ж.Д.',
            'distMinWay': '0',
            'distRecipID': '5005053',
            'distRecipOKPO': '82365518',
            'distRecipName': 'Акционерное общество "АТРИУМ"',
            'distRecipAddressID': '0',
            'distRecipAddress': '654007, КЕМЕРОВСКАЯ ОБЛАСТЬ - КУЗБАСС, г. Новокузнецк, ул. Павловского - д. 11 А - оф. 508, тел: 8(3842) 44-00-81,8-910-407-2528',
            'distRecipTGNL': '4444',
            'distSign': '101010',
            'distCarrierID': '1',
            'distPowerKind': '1'
        }
    ],
    'invSPC': [
        {
            'spcTranspClauseID': '1213',
            'spcTranspClauseDesc': 'Из ремонта'
        },
        {
            'spcTranspClauseID': '1293',
            'spcTranspClauseDesc': 'Дата и время передачи порожнего вагона перевозчику',
            'spcCustomText': '08.03.2025 23:59:59'
        },
        {
            'spcTranspClauseID': '1418',
            'spcTranspClauseDesc': 'Согласен на предъявление (прием) вагона к перевозке ранее указанной даты'
        }
    ],
    'invDOC': {
        'docTypeID': '1175',
        'docNumber': '1'
    },
    'invCar': [
        {
            'carTypeID': '60',
            'carTypeCode': '60',
            'carTypeName': 'полувагоны',
            'carNumber': '53128914',
            'carOrder': '1',
            'carOwnerCountryCode': '643',
            'carOwnerCountryName': 'РОССИЯ',
            'carOwnerTypeID': '1',
            'carOwnerTypeName': 'Собственный',
            'carOwnerID': '622082',
            'carOwnerOKPO': '42876737',
            'carOwnerName': 'Общество с ограниченной ответственностью "Транспортные Технологии"',
            'carTonnage': '69.0',
            'carAxles': '4',
            'carVolume': '88',
            'carWeightDep': '238',
            'carWeightDepReal': '0',
            'carWeightGross': '23800',
            'carWeightNet': '0',
            'carGuideCount': '0',
            'carRolls': '1',
            'carConnectCode': '0',
            'carIsCover': '0',
            'carLength': '13.920'
        },
        {
            'carTypeID': '60',
            'carTypeCode': '60',
            'carTypeName': 'полувагоны',
            'carNumber': '53426912',
            'carOrder': '2',
            'carOwnerCountryCode': '643',
            'carOwnerCountryName': 'РОССИЯ',
            'carOwnerTypeID': '1',
            'carOwnerTypeName': 'Собственный',
            'carOwnerID': '647023',
            'carOwnerOKPO': '40623142',
            'carOwnerName': 'Общество с ограниченной ответственностью "АБЦ-РЕЙЛ"',
            'carTonnage': '69.5',
            'carAxles': '4',
            'carVolume': '88',
            'carWeightDep': '240',
            'carWeightDepReal': '0',
            'carWeightGross': '24000',
            'carWeightNet': '0',
            'carGuideCount': '0',
            'carRolls': '1',
            'carConnectCode': '0',
            'carIsCover': '0',
            'carLength': '13.920'
        },
        {
            'carTypeID': '60',
            'carTypeCode': '60',
            'carTypeName': 'полувагоны',
            'carNumber': '56063647',
            'carOrder': '3',
            'carOwnerCountryCode': '643',
            'carOwnerCountryName': 'РОССИЯ',
            'carOwnerTypeID': '1',
            'carOwnerTypeName': 'Собственный',
            'carOwnerID': '622082',
            'carOwnerOKPO': '42876737',
            'carOwnerName': 'Общество с ограниченной ответственностью "Транспортные Технологии"',
            'carTonnage': '69.0',
            'carAxles': '4',
            'carVolume': '88',
            'carWeightDep': '238',
            'carWeightDepReal': '0',
            'carWeightGross': '23800',
            'carWeightNet': '0',
            'carGuideCount': '0',
            'carRolls': '1',
            'carConnectCode': '0',
            'carIsCover': '0',
            'carLength': '13.920'
        }
    ],
    'invTranspClause': {
        'transpClauseId': '829',
        'transpClauseName': 'Перевозка собственных или арендованных вагонов в/из ремонта',
        'transpClauseTarifMark': '50'
    },
    'invFormPPSign': '0',
    'invTranspPurposeID': '1'
}
